# Generated by Django 4.1.2 on 2022-10-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
